const timeFields=["crew","lunchIn","lunchOut","wrap"].map(id=>document.getElementById(id));
const totalValue=document.getElementById("totalValue"),lunchValue=document.getElementById("lunchValue"),workedValue=document.getElementById("workedValue"),result=document.getElementById("result"),errorDialog=document.getElementById("errorDialog"),errorMessage=document.getElementById("errorMessage"),errorOk=document.getElementById("errorOk");
function digitsOnly(input){input.value=input.value.replace(/\D/g,"").slice(0,Number(input.maxLength)||Infinity)}
function parseFilmTime(value){if(!/^\d{4}$/.test(value))throw new Error("Enter each time as four digits, for example 0930.");const hours=Number(value.slice(0,2)),minutes=Number(value.slice(2));if(minutes>59)throw new Error("Minutes must be between 00 and 59.");return hours*60+minutes}
function formatDuration(totalMinutes){const hours=Math.floor(totalMinutes/60),minutes=totalMinutes%60;if(hours===0)return `${minutes} minute${minutes===1?"":"s"}`;if(minutes===0)return `${hours} hour${hours===1?"":"s"}`;return `${hours} hour${hours===1?"":"s"} ${minutes} minute${minutes===1?"":"s"}`}
function showError(message){errorMessage.textContent=message;errorDialog.hidden=false;errorOk.focus()}
function calculate(){try{let[crew,lunchIn,lunchOut,wrap]=timeFields.map(field=>parseFilmTime(field.value));const times=[crew,lunchIn,lunchOut,wrap],adjusted=[times[0]];for(let i=1;i<times.length;i+=1){let current=times[i];while(current<adjusted[i-1])current+=1440;adjusted.push(current)}[crew,lunchIn,lunchOut,wrap]=adjusted;const totalDay=wrap-crew,lunch=lunchOut-lunchIn,worked=totalDay-lunch;if(lunch<=0)throw new Error("Lunch Out must be after Lunch In.");if(totalDay<=0)throw new Error("Wrap must be after Crew Call.");if(worked<0)throw new Error("The calculated worked time cannot be negative.");totalValue.textContent=formatDuration(totalDay);lunchValue.textContent=formatDuration(lunch);workedValue.textContent=formatDuration(worked);result.classList.add("success")}catch(error){showError(error.message)}}
function clearTimeFields(){timeFields.forEach(field=>field.value="");[totalValue,lunchValue,workedValue].forEach(value=>value.textContent="—");result.classList.remove("success");timeFields[0].focus()}
function pageTotal(){const wholes=[...document.querySelectorAll(".page-whole")],eighths=[...document.querySelectorAll(".page-eighth")];return wholes.reduce((total,whole,index)=>total+(Number(whole.value||0)*8)+Number(eighths[index].value||0),0)}
function formatPages(total){if(total===0)return "0/8";const whole=Math.floor(total/8),eighth=total%8;return whole===0?`${eighth}/8`:`${whole} ${eighth}/8`}
function updatePages(){document.getElementById("pagesValue").textContent=formatPages(pageTotal())}
function updateMinutes(){const minutes=[...document.querySelectorAll(".minute-minutes")],seconds=[...document.querySelectorAll(".minute-seconds")];const totalSeconds=minutes.reduce((total,minute,index)=>total+(Number(minute.value||0)*60)+Number(seconds[index].value||0),0),totalMinutes=Math.floor(totalSeconds/60),remainingSeconds=totalSeconds%60;document.getElementById("minutesValue").textContent=`${String(totalMinutes).padStart(2,"0")}:${String(remainingSeconds).padStart(2,"0")}`}
function updateSetups(){const total=[...document.querySelectorAll(".setup-input")].reduce((sum,input)=>sum+Number(input.value||0),0);document.getElementById("setupsValue").textContent=String(total).padStart(2,"0")}
async function copyResult(event){const value=event.currentTarget.textContent;if(value==="—")return;try{await navigator.clipboard.writeText(value)}catch{const temporary=document.createElement("textarea");temporary.value=value;temporary.style.position="fixed";temporary.style.opacity="0";document.body.append(temporary);temporary.select();document.execCommand("copy");temporary.remove()}const button=event.currentTarget,original=value;button.textContent="Copied!";button.classList.add("copied");window.setTimeout(()=>{button.textContent=original;button.classList.remove("copied")},1000)}
document.querySelectorAll(".digits-only").forEach(input=>input.addEventListener("input",()=>digitsOnly(input)));document.querySelectorAll(".digits-eighth").forEach(input=>input.addEventListener("input",()=>input.value=input.value.replace(/[^0-7]/g,"").slice(0,1)));document.querySelectorAll(".page-whole,.page-eighth").forEach(input=>input.addEventListener("input",updatePages));document.querySelectorAll(".minute-minutes,.minute-seconds").forEach(input=>input.addEventListener("input",updateMinutes));document.querySelectorAll(".setup-input").forEach(input=>input.addEventListener("input",updateSetups));timeFields.forEach((field,index)=>field.addEventListener("keydown",event=>{if(event.key==="Enter"){event.preventDefault();index<timeFields.length-1?timeFields[index+1].focus():calculate()}}));document.querySelectorAll(".copy-value").forEach(button=>button.addEventListener("click",copyResult));document.getElementById("calculate").addEventListener("click",calculate);document.getElementById("clear").addEventListener("click",clearTimeFields);errorOk.addEventListener("click",()=>errorDialog.hidden=true);document.addEventListener("keydown",event=>{if(event.ctrlKey&&event.key==="Enter"){event.preventDefault();calculate()}if(event.key==="Escape")errorDialog.hidden=true});if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));updatePages();updateMinutes();updateSetups();timeFields[0].focus();
